### ISSUE TITLE
Has this been tested against anything other than itself

### ISSUE THREAD

**Issue by eliotmansfield** [Makerfabs/Maduino-CANbus-RS485#1]
If I set the speed to 500kb/s and connect it to another arduino running canhacker, i have to set the speed to 250kb/s - also if i connect it to my car, again I have to set the ECU to 250kbs/s but the maduino to 500kb/s - also the can_receiver code never receives anything (which uses interrupts) but the can_sender does work in both directions to canhacker and my car ECU - but i have to set it to the wrong speed for it to work.

My module was bought from makerfabs tindie store.

**Comment by HazzyDave** [comment]
You have this issue if you set for 16MHZ clock speed. You need to set it for 8MHZ.

**Comment by HazzyDave** [comment]
while (CAN_OK != CAN.begin(CAN_500KBPS,MCP_8MHz)

**Comment by HazzyDave** [comment]
Mate you can close this issue if it fixed the problem
