### ISSUE TITLE
CAN speeds are not correct

### ISSUE THREAD

**Issue by HazzyDave** [Makerfabs/Maduino-CANbus-RS485#2]
If I set the speed to 500K my reciever needs to be set to 250K. If i set it to 1000K then my reciever gets it at 500K. 

I have tried the example and another sketch that works perfect on my other boards but this one has the same result of the defined speed ending being cut in half when it sends...

**Comment by HazzyDave** [comment]
Although not stated anywhere or available in the dem sketch you have to be set to 8MHZ not 16MHZ for the speed to be correct.

**Comment by eliotmansfield** [comment]
this line in mcp2515.h?

`"#define MCP2515_DEFAULT_CLOCK_FREQUENCY 16e6" `

**Comment by HazzyDave** [comment]
I actrually used a different set of examples designed for the 2515 that allows you to set the clock speed in the init line of the sketch. I didn't look through thier examples to solve it. 

The line you posted looks like it could be the fix. Although I have contemplated removing their 8MHZ crystal and swapping in a 16MHZ. 
I am using Fowlers duo can library since most of what I do is with dual can bus.  I made a quick mod to the sketch below to test with  a can sniffer. The print commands don't work but the board works as it should. 

If you don't want to complicate your sketches by importing another can library. Just download the fowler files makde a sketch and manually add the files to the sketch from the sketch tab at the bottom. That way they will be built into the sketch and not complicate your library and cause issues later. 

// CAN Send Example
//

#include <mcp_can.h>
#include <SPI.h>
#define SERIAL SerialUSB
MCP_CAN CAN0(3);     // Set CS

void setup()
{
  Serial.begin(115200);
  Serial1.begin(115200);
  // Initialize MCP2515 running at 8MHz with a baudrate of 1000kb/s (1MBs) and the masks and filters disabled.
  if(CAN0.begin(MCP_ANY, CAN_1000KBPS, MCP_8MHZ) == CAN_OK) Serial1.println("MCP2515 Initialized Successfully!");
  else Serial1.println("Error Initializing MCP2515...");

  CAN0.setMode(MCP_NORMAL);   // Change to normal mode to allow messages to be transmitted
}

byte data[8] = {0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07};

void loop()
{
  // send data:  ID = 0x100, Standard CAN Frame, Data length = 8 bytes, 'data' = array of data bytes to send
  byte sndStat = CAN0.sendMsgBuf(0x100, 0, 8, data);
  if(sndStat == CAN_OK){
    Serial1.println("Message Sent Successfully!");
  } else {
    Serial1.println("Error Sending Message...");
  }
  delay(50);   // send data per 50ms

**Comment by HazzyDave** [comment]
Here you go mate. Just set your can up as follows. For some reason they didn't include the clock in the setup. After checking the source code it made sense. 

while (CAN_OK != CAN.begin(CAN_500KBPS,MCP_8MHz)
